CREATE TABLE IF NOT EXISTS account (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    balance DECIMAL(19, 4) NOT NULL DEFAULT 0.00
);

CREATE INDEX IF NOT EXISTS idx_account_name ON account(name);


CREATE TABLE IF NOT EXISTS transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sender_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id, timestamp)
) PARTITION BY RANGE (timestamp);

CREATE INDEX IF NOT EXISTS idx_transaction_sender_recipient_id ON transaction(sender_id, recipient_id);



-- Partitions for 2025
CREATE TABLE IF NOT EXISTS transaction_y2025m05 PARTITION OF transaction
    FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');

CREATE TABLE IF NOT EXISTS transaction_y2025m06 PARTITION OF transaction
    FOR VALUES FROM ('2025-06-01') TO ('2025-07-01');

CREATE TABLE IF NOT EXISTS transaction_y2025m07 PARTITION OF transaction
    FOR VALUES FROM ('2025-07-01') TO ('2025-08-01');

CREATE TABLE IF NOT EXISTS transaction_y2025m08 PARTITION OF transaction
    FOR VALUES FROM ('2025-08-01') TO ('2025-09-01');

CREATE TABLE IF NOT EXISTS transaction_y2025m09 PARTITION OF transaction
    FOR VALUES FROM ('2025-09-01') TO ('2025-10-01');

CREATE TABLE IF NOT EXISTS transaction_y2025m10 PARTITION OF transaction
    FOR VALUES FROM ('2025-10-01') TO ('2025-11-01');

CREATE TABLE IF NOT EXISTS transaction_y2025m11 PARTITION OF transaction
    FOR VALUES FROM ('2025-11-01') TO ('2025-12-01');

CREATE TABLE IF NOT EXISTS transaction_y2025m12 PARTITION OF transaction
    FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');


COMMENT ON TABLE account IS 'Stores account information including balance.';
COMMENT ON COLUMN account.id IS 'Unique identifier for the account.';
COMMENT ON COLUMN account.name IS 'Name of the account holder.';
COMMENT ON COLUMN account.balance IS 'Current balance of the account.';

COMMENT ON TABLE transaction IS 'Stores financial transactions, partitioned by timestamp.';
COMMENT ON COLUMN transaction.id IS 'Unique identifier for the transaction.';
COMMENT ON COLUMN transaction.sender_id IS 'ID of the account sending the funds.';
COMMENT ON COLUMN transaction.recipient_id IS 'ID of the account receiving the funds.';
COMMENT ON COLUMN transaction.amount IS 'Amount of money transferred.';
COMMENT ON COLUMN transaction.timestamp IS 'Timestamp when the transaction occurred, used for partitioning.';

