spring:
  application:
    name: instant-payment-api
  datasource:
    url: jdbc:postgresql://db:5432/payments
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      client-id: instant-payment-api
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      compression-type: snappy
  threads:
    virtual:
      enabled: true
  data:
    redis:
      repositories:
        enabled: false
      host: redis
      port: 6379
      timeout: PT3S

app:
  kafka-topics:
    transaction-created: transaction.created
  redis:
    cache-name-prefix: ${spring.application.name}
    cache:
      unsentMessages:
        time-to-live: PT24H
  dead-letter:
    resend-interval: PT5S

